### PR TITLE
fix: resolve undefined version in download links and update macOS package names

### LINKED ISSUE #2869: Download links on the web site are currently not working
https://github.com/JabRef/JabRefOnline/blob/0c4f11538f4ea4b754825583674cf0c8be1fdf57/pages/download/[[os]].vue#L24

Hei, 
I tried today the download from the web page, and it seams to me that the lower part of that function - adding the specific version is currently not working. 
It sends me to the URL https://github.com/JabRef/jabref/releases/download/vundefined which is not reachable. 

Does someone know what the problem here is?

### PR DESCRIPTION
**Pull request by D-Prasanth-Kumar**
### 🔗 Linked issue

Resolves #2869
Resolves https://discourse.jabref.org/t/the-osx-download-link-s-on-the-main-site-are-broken/9048

### 📚 Description

This PR addresses the broken download links and updates the macOS package naming conventions for upcoming releases.

-> **Fixed vundefined bug in download URLs:** Added validation to check if latestRelease is successfully fetched from the API. If the API fails, it safely falls back to redirecting the user to the releases/latest GitHub page instead of generating a broken URL.

-> **Updated macOS package names:** Adapted the macOS download logic to use the new _silicon and _intel suffixes for .dmg and .pkg files as seen on builds.jabref.org.

-> **Added backward compatibility for v5.x:** Implemented a major version check (majorVersion >= 6) to ensure that current stable v5.15 downloads (which still use the old -arm64 and default naming) do not break.

### CODE REVIEW

File: pages/download/[[os]].vue [hunk 1]
```diff
@@ -38,25 +38,30 @@ definePageMeta({
...
+            mac_arm64_dmg: majorVersion >= 6 ? `/JabRef-${latestRelease}_silicon.dmg` : `/JabRef-${latestRelease}-arm64.dmg`,
+            mac_arm64_pkg: majorVersion >= 6 ? `/JabRef-${latestRelease}_silicon.pkg` : `/JabRef-${latestRelease}-arm64.pkg`,
+            mac_x86_64_dmg: majorVersion >= 6 ?  `/JabRef-${latestRelease}_intel.dmg` : `/JabRef-${latestRelease}.dmg`,
+            mac_x86_64_pkg: majorVersion >= 6 ? `/JabRef-${latestRelease}_intel.pkg` : `/JabRef-${latestRelease}.pkg`,
             linux_deb: `/jabref_${latestRelease}_amd64.deb`,
             linux_rpm: `/jabref-${latestRelease}-1.x86_64.rpm`,
             linux_tar_gz: `/JabRef-${latestRelease}-portable_linux.tar.gz`,
           }[os] ?? ''
+      } else {
+        downloadUrl = 'https://github.com/JabRef/jabref/releases/latest'
```
Comment (tobiasdiez) [inline pages/download/[[os]].vue]: This URL is now used three times. Please extract it to a new constant.

File: prisma.config.ts [hunk 2]
```diff
@@ -2,7 +2,7 @@
  * Prisma configuration file
  * See: https://www.prisma.io/docs/orm/reference/prisma-config-reference
  */
-
+import 'dotenv/config';
```
Comment (tobiasdiez) [inline prisma.config.ts]: why do you need to set this? we don't use `env` here in the prisma config

**Review by tobiasdiez — CHANGES_REQUESTED** [review]
Thanks!

File: pages/download/[[os]].vue [hunk 3]
```diff
@@ -38,25 +38,30 @@ definePageMeta({
...
+        downloadUrl += `v${latestRelease}`
         downloadUrl +=
           {
             win_msi: `/JabRef-${latestRelease}.msi`,
             win_zip: `/JabRef-${latestRelease}-portable_windows.zip`,
-            mac_arm64_dmg: `/JabRef-${latestRelease}-arm64.dmg`,
-            mac_arm64_pkg: `/JabRef-${latestRelease}-arm64.pkg`,
-            mac_x86_64_dmg: `/JabRef-${latestRelease}.dmg`,
-            mac_x86_64_pkg: `/JabRef-${latestRelease}.pkg`,
+            mac_arm64_dmg: majorVersion >= 6 ? `/JabRef-${latestRelease}_silicon.dmg` : `/JabRef-${latestRelease}-arm64.dmg`,
```
Comment (tobiasdiez) [inline pages/download/[[os]].vue]: @Siedlerchr are these new names correct?

**Comment by D-Prasanth-Kumar** [comment]
> Perhaps a stupid question (I'm tired), but why does the e2e test needs to be changed?

in the before [[os]].vue file we mentioned the FALLBACK_DOWNLOAD_URL = `https://github.com/JabRef/jabref/releases/latest` , so if someone visits /download , it now redirects to releases/latest instead of the old broken releases/download/ link. i just updated the test to expect the new URL.

**Review by tobiasdiez — APPROVED** [review]
Right, thanks again!

**Comment by D-Prasanth-Kumar** [comment]
> Right, thanks again!

Anytime!
